### ISSUE TITLE
CUDA out of memory if specify --norm_mode clade

### ISSUE THREAD

**Issue by chenpei-cs** [tzt101/CLADE#1]

**Comment by tzt101** [comment]
This may caused by the affine_gather() in the models/networks/normalization.py. In order to use torch.gather(), we expand the tensor which need more memory. Now, we have reimplemented two equivalent functions, affine_einsum() and affine_embed(), which occupy less memory.
![图片](https://user-images.githubusercontent.com/26423710/108932021-9d7de900-7683-11eb-948f-2380cae73436.png)

**Comment by chenpei-cs** [comment]
> This may caused by the affine_gather() in the models/networks/normalization.py. In order to use torch.gather(), we expand the tensor which need more memory. Now, we have reimplemented two equivalent functions, affine_einsum() and affine_embed(), which occupy less memory.
> ![图片](https://user-images.githubusercontent.com/26423710/108932021-9d7de900-7683-11eb-948f-2380cae73436.png)

**Comment by chenpei-cs** [comment]
> This may caused by the affine_gather() in the models/networks/normalization.py. In order to use torch.gather(), we expand the tensor which need more memory. Now, we have reimplemented two equivalent functions, affine_einsum() and affine_embed(), which occupy less memory.
> ![图片](https://user-images.githubusercontent.com/26423710/108932021-9d7de900-7683-11eb-948f-2380cae73436.png)

Thank you very much!
